# This is currently a no-op Travis configuration so that the GitHub repo
# can get a Checks API callback to ensure that branches are up-to-date before
# merging. Eventually we could add static linting.
#
# The build itself is done by:
# https://ci.lsst.codes/blue/organizations/jenkins/sqre%2Finfra%2Fdocumenteer/activity

language: python
python:
  - "3.6"
script:
  - "true"
